### ISSUE TITLE
Concurrent Standup questions

### ISSUE THREAD

**Issue by jsmestad** [sofetch/slack-standup-bot#21] opened 2015-11-12 18:27 UTC
Couple things I noticed trying this out:

1. The bot asks for updates from multiple people at a time. Is this maybe due to using `puma` as the web server?
2. ~~Configuring an 'ignore' list for spectators like managers would be good. I often facilitate the standup, but I often will `-skip` myself~~ Addressed below

**Comment by cgrusden** [comment] 2015-11-12 18:49
My immediate response to #2 is... why are you skipping yourself? Shouldn't you the management say your standup for solidarity?

**Comment by jsmestad** [comment] 2015-11-12 18:51
@cgrusden its a good point. I think the thought right now is that the scrum master is just there to facilitate (total admin role). I could see teams wanting an either/or. The other use for 'ignore list' is if that channel happens to also have a bot user or something else in there.

**Comment by cgrusden** [comment] 2015-11-12 18:53
Understood. 

For your first question, it may be repetitive on the daily basis, but you could: -vacation @yourself ?  That will skip you for the day.  As it stands, since it's open-source, and the functionality exists, I don't see adding that as a good idea at the moment.

**Comment by jsmestad** [comment] 2015-11-12 18:56
Got it. Any idea on the concurrency issue? We had the bot send the following today:

<img width="860" alt="screen shot 2015-11-12 at 11 55 50 am" src="https://cloud.githubusercontent.com/assets/16150/11127983/5cec9342-8934-11e5-81dd-fdb3471a2973.png">

**Comment by santiagodoldan** [comment] 2015-11-12 19:34
about the concurrency issue, we support multiple standups at the same time because a user is able to edit a question when another user is doing its standup.

but, looking at the screenshot, we may not allow the admin to set non active users n/a, at that point the admin should only be able to set @andygrove n/a.

another thing, -n/a: supports only one user at a time.

**Comment by santiagodoldan** [comment] 2016-01-04 21:39
I'm going to close this Issue as the app is able to manage multiple standups at the same time. it's a feature and not a bug.

**Closed by santiagodoldan** 2016-01-04 21:39 UTC
